# Generated by Django 4.1.4 on 2023-09-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caselist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
